### ISSUE TITLE
Double tap detect

### ISSUE THREAD

**Issue by cybri0nix** [vsesh/shri2017-sensor#1]
gesture-controller.js:32

if (this._lastEventTypes.indexOf('start stop start stop') > -1) {
                this._lastEventTypes = '';
                // to do somethin awesome!
                return;
            }

Двойной tap не ловится, т.к. вместо stop, по-моему, должно быть "end" => start end start end

**Comment by vsesh** [comment]
Верно. Это остатки старого кода. Поправил
